name: recipe_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_route: ^9.2.2
  get_it: ^7.7.0
  talker_flutter: ^4.4.1
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  talker_dio_logger: ^4.4.1
  talker_bloc_logger: ^4.4.1
  provider: ^6.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/logo/logo.png"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
  macos:
    generate: true
    image_path: "assets/logo/logo.png"
